"""Generate MLIR transform schedule for XeGPU attention using only upstream transforms.

This schedule is a counterpart to `fused_attention_schedule`, restricted to
tiling and fusion primitives that are available in upstream MLIR. In particular
it does *not* use the `transform_ext.replace_with_fused_attention` extension,
which rewrites the innermost computation into an online-softmax (flash
attention) loop at the vector level.

Upstream MLIR has no transform that fuses a softmax into a loop over the
reduction dimension it reduces over: the row max and the row sum of exp both
need the whole row of Q@K^T before the normalized weights can be formed. The
only way to keep the [wg_rows, n_ctx] score matrix out of registers with
upstream primitives is therefore to *recompute* Q@K^T once per softmax
reduction, i.e. a multi-pass attention:

    pass 1 (loop over kv tiles):  m = max_k(Q@K^T * scale)
    pass 2 (loop over kv tiles):  l = sum_k(exp(Q@K^T * scale - m))
    pass 3 (loop over kv tiles):  O = sum_k (exp(Q@K^T * scale - m) / l) @ V

Each pass is a reduction over the k (n_ctx of K/V) dimension and is generated by
`transform.structured.tile_reduction_using_for` / `tile_using_for`, with the
Q@K^T chain fused in with `transform.structured.fuse_into_containing_op`. The
cost of staying upstream-only is 3 evaluations of Q@K^T instead of 1, i.e. 2x
the multiply-accumulate work of a fused kernel.
"""

from mlir import ir
from mlir.dialects import transform
from mlir.dialects.transform import structured, loop, xegpu
from mlir.dialects.transform import bufferization as transform_bufferization
from mlir.dialects.bufferization import LayoutMapOption
from mlir.dialects.transform.vector import (
    apply_patterns_vector_cast_away_vector_leading_one_dim,
    apply_patterns_vector_drop_unit_dims_with_shape_cast,
)

from lighthouse.pipeline.helper import (
    canonicalize,
    match,
    match_and_split,
    PipelineInterrupt,
    apply_registered_pass,
)
from lighthouse.schedule import schedule_boilerplate


def attention_upstream_schedule(
    stop_at_stage: str | None = None,
    parameters: dict | None = None,
) -> ir.Module:
    """
    Generate transform schedule for the upstream-only attention kernel.

    Args:
        stop_at_stage: Optional stage name to stop early (for debugging)
        parameters: Dictionary with scheduling parameters (see the example driver)

    Returns:
        MLIR module containing the transform schedule
    """
    assert parameters is not None, "Schedule parameters must be provided"

    with schedule_boilerplate() as (schedule, named_seq):
        anytype = transform.AnyOpType.get()
        func = match(named_seq.bodyTarget, ops={"func.func"})
        payload_mod = transform.get_parent_op(
            anytype,
            func,
            op_name="builtin.module",
            deduplicate=True,
        )

        try:
            bundle_xegpu_attention_upstream_schedule(
                payload_mod,
                parameters=parameters,
                stop_at_stage=stop_at_stage or "",
            )
        except PipelineInterrupt:
            pass
        finally:
            transform.yield_()

    return schedule


def bundle_xegpu_attention_upstream_schedule(
    mod: ir.Value[transform.AnyOpType],
    parameters: dict,
    stop_at_stage: str = "",
) -> ir.Value[transform.AnyOpType]:
    """Schedule for lowering the attention payload to xegpu wg level."""

    if stop_at_stage == "initial":
        raise PipelineInterrupt()

    anytype = transform.AnyOpType.get()

    # ------------------------------------------------------------------
    # Work group level: tile the parallel dimensions of the last matmul
    # (attention_weights @ V) and fuse the whole attention chain into it.
    # ------------------------------------------------------------------
    matmul_ops = match_and_split(mod, ops={"linalg.batch_matmul"}, nhandles=2)
    last_matmul = matmul_ops[1]
    func = transform.get_parent_op(
        anytype,
        last_matmul,
        op_name="func.func",
        deduplicate=True,
    )

    wg_rows = parameters["wg_rows"]
    _, forall_loop = structured.structured_tile_using_forall(
        anytype,
        anytype,
        last_matmul,
        num_threads=[],
        tile_sizes=[],
        static_tile_sizes=(1, wg_rows, 0, 0),
    )
    # Fuse the zero initialization of the output (tensor.empty + fill).
    tiled_matmul_init = transform.get_producer_of_operand(
        anytype, forall_loop, operand_number=0
    )
    _, forall_loop = structured.structured_fuse_into_containing_op(
        anytype,
        anytype,
        producer_op=tiled_matmul_init,
        containing_op=forall_loop,
    )
    transform.apply_cse(func)
    canonicalize(func)

    # Decompose softmax into generic ops (max, sub+exp, sum, div).
    softmax_op = match_and_split(func, ops={"linalg.softmax"}, nhandles=1)[0]
    structured.structured_decompose_interface(anytype, softmax_op)
    transform.apply_cse(func)
    canonicalize(func)

    # Fuse the 4 softmax generics into the work group loop, consumer first.
    generic_ops = match_and_split(func, ops={"linalg.generic"}, nhandles=4)
    for generic_op in reversed(generic_ops):
        _, forall_loop = structured.structured_fuse_into_containing_op(
            anytype,
            anytype,
            producer_op=generic_op,
            containing_op=forall_loop,
        )
    transform.apply_cse(func)
    canonicalize(func)

    # The max and sum reductions are initialized by linalg.fill; fuse those too.
    fill_ops = match_and_split(func, ops={"linalg.fill"}, nhandles=5)
    max_fill_op = fill_ops[2]
    add_fill_op = fill_ops[3]
    for fill_op in [max_fill_op, add_fill_op]:
        _, forall_loop = structured.structured_fuse_into_containing_op(
            anytype,
            anytype,
            producer_op=fill_op,
            containing_op=forall_loop,
        )
    transform.apply_cse(func)
    canonicalize(func)

    # Fuse the remaining Q@K^T chain into the work group loop.
    linalg_mul_op = match_and_split(func, ops={"linalg.mul"}, nhandles=1)[0]
    first_matmul = transform.get_producer_of_operand(
        anytype, linalg_mul_op, operand_number=0
    )
    scale_fill_op = transform.get_producer_of_operand(
        anytype, linalg_mul_op, operand_number=1
    )
    transpose_op = transform.get_producer_of_operand(
        anytype, first_matmul, operand_number=1
    )
    matmul_fill_op = transform.get_producer_of_operand(
        anytype, first_matmul, operand_number=2
    )
    for op in [
        linalg_mul_op,
        scale_fill_op,
        first_matmul,
        matmul_fill_op,
        transpose_op,
    ]:
        _, forall_loop = structured.structured_fuse_into_containing_op(
            anytype,
            anytype,
            producer_op=op,
            containing_op=forall_loop,
        )
    transform.apply_cse(func)
    canonicalize(func)

    if stop_at_stage == "wg-tiled":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Reduction (kv) level: tile the k dimension of each of the three
    # reductions over n_ctx and recompute the Q@K^T chain inside each loop.
    #
    # Upstream cannot fuse the softmax reductions with the P@V contraction into
    # a single kv loop (that requires online rescaling of the accumulator), so
    # each reduction gets its own loop:
    #   loop 1: m = max_k(S)
    #   loop 2: l = sum_k(exp(S - m))
    #   loop 3: O = sum_k (exp(S - m) / l) @ V
    # with S = Q@K^T * scale recomputed tile by tile in every loop.
    # ------------------------------------------------------------------
    # The loops are created back to front (P@V, then sum, then max). Ordering
    # matters: `fuse_into_containing_op` only supports a fused producer with
    # remaining users *after* the containing op when that op is an scf.forall
    # (see replaceForAllWithNewSignature, which casts the containing op to
    # scf.forall unconditionally). Creating the loops back to front means every
    # producer that is recomputed still has all of its remaining users *before*
    # the loop it is fused into, which keeps that path out of the way.
    kv_tile = parameters["kv_tile_size"]
    # The max/sum passes do a single DPAS per K tile, so they tolerate (and
    # usually want) a different tile size than the P@V pass.
    softmax_kv_tile = parameters.get("softmax_kv_tile_size") or kv_tile

    pv_matmul = match_and_split(func, ops={"linalg.batch_matmul"}, nhandles=2)[1]

    def score_chain_from(consumer_of_scores):
        """Producers of the scaled scores S, ordered consumer first."""
        mul_op = transform.get_producer_of_operand(
            anytype, consumer_of_scores, operand_number=0
        )
        qk_matmul = transform.get_producer_of_operand(anytype, mul_op, operand_number=0)
        scale_fill = transform.get_producer_of_operand(
            anytype, mul_op, operand_number=1
        )
        transpose = transform.get_producer_of_operand(
            anytype, qk_matmul, operand_number=1
        )
        qk_fill = transform.get_producer_of_operand(
            anytype, qk_matmul, operand_number=2
        )
        return [mul_op, scale_fill, qk_matmul, qk_fill, transpose]

    def fuse_all_into(producers, containing_loop):
        for producer in producers:
            _, containing_loop = structured.structured_fuse_into_containing_op(
                anytype,
                anytype,
                producer_op=producer,
                containing_op=containing_loop,
            )
        return containing_loop

    # Anchors for all three loops, matched while the chain is still a straight
    # line. `max_op` and `sum_op` are only consumed by their own tiling step, so
    # they stay valid across the fusions of the later loops.
    div_op = transform.get_producer_of_operand(anytype, pv_matmul, operand_number=0)
    exp_op = transform.get_producer_of_operand(anytype, div_op, operand_number=0)
    sum_op = transform.get_producer_of_operand(anytype, div_op, operand_number=1)
    max_op = transform.get_producer_of_operand(anytype, exp_op, operand_number=1)

    # Loop 3: the P@V contraction over the n_ctx (k) dimension, with the
    # normalized weights recomputed per tile.
    score_chain = score_chain_from(exp_op)
    pv_tiling = structured.TileUsingForOp(
        [anytype], pv_matmul, sizes=[0, 0, 0, kv_tile]
    )
    pv_loop = pv_tiling.loops[0]
    pv_loop = fuse_all_into([div_op, exp_op] + score_chain, pv_loop)
    transform.apply_cse(func)
    canonicalize(func)

    # Loop 2: row sum of exp(S - m).
    exp_op = transform.get_producer_of_operand(anytype, sum_op, operand_number=0)
    score_chain = score_chain_from(exp_op)
    _, _, _, sum_loop = structured.structured_tile_reduction_using_for(
        [anytype],
        anytype,
        anytype,
        anytype,
        sum_op,
        tile_sizes=[0, 0, softmax_kv_tile],
    )
    sum_loop = fuse_all_into([exp_op] + score_chain, sum_loop)
    transform.apply_cse(func)
    canonicalize(func)

    # Loop 1: row max of S.
    score_chain = score_chain_from(max_op)
    _, _, _, max_loop = structured.structured_tile_reduction_using_for(
        [anytype],
        anytype,
        anytype,
        anytype,
        max_op,
        tile_sizes=[0, 0, softmax_kv_tile],
    )
    max_loop = fuse_all_into(score_chain, max_loop)
    transform.apply_cse(func)
    canonicalize(func)

    if stop_at_stage == "kv-tiled":
        raise PipelineInterrupt()

    # Drop the unit batch dimension introduced by the work group tiling: unit
    # dims confuse the xegpu lowering, so get rid of them while still on linalg.
    # The rank-reducing patterns only rewrite generic ops, so the named ops
    # (batch_matmul, transpose, fill, reduce) have to be generalized first.
    named_ops = match(
        func,
        ops={
            "linalg.batch_matmul",
            "linalg.transpose",
            "linalg.fill",
            "linalg.reduce",
            "linalg.mul",
        },
    )
    structured.structured_generalize(anytype, named_ops)
    with ir.InsertionPoint(transform.apply_patterns(func).patterns):
        structured.apply_patterns_linalg_fold_unit_extent_dims_via_slices()
    transform.apply_cse(func)
    canonicalize(func)

    if stop_at_stage == "unit-dims-dropped":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Vectorize
    # ------------------------------------------------------------------
    func = structured.VectorizeChildrenAndApplyPatternsOp(
        func,
        fold_type_extensions_into_contract=True,
    ).result
    transform.apply_cse(func)
    canonicalize(func)
    with ir.InsertionPoint(transform.apply_patterns(func).patterns):
        apply_patterns_vector_cast_away_vector_leading_one_dim()
        apply_patterns_vector_drop_unit_dims_with_shape_cast()
    transform.apply_cse(func)
    canonicalize(func)

    # The three reduction loops carry their accumulator as a tensor with a
    # transfer_read/transfer_write pair inside the loop, which bufferizes to a
    # scratch allocation. Hoisting the transfers turns the accumulators into
    # loop-carried vectors, i.e. registers.
    kv_loops = match(func, ops={"scf.for"})
    transform.apply_licm(kv_loops)
    loop.loop_hoist_loop_invariant_subsets(kv_loops)
    func = structured.structured_hoist_redundant_vector_transfers(anytype, func)
    transform.apply_cse(func)
    canonicalize(func)

    if stop_at_stage == "vectorized":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Bufferize
    # ------------------------------------------------------------------
    mod = apply_registered_pass(mod, "eliminate-empty-tensors")
    identity_layout = LayoutMapOption.IdentityLayoutMap
    mod = transform_bufferization.OneShotBufferizeOp(
        mod,
        allow_return_allocs_from_loops=True,
        bufferize_function_boundaries=True,
        function_boundary_type_conversion=identity_layout,
    ).result
    mod = apply_registered_pass(mod, "fold-memref-alias-ops")
    transform.apply_cse(mod)
    canonicalize(mod)

    if stop_at_stage == "bufferized":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Convert to gpu.launch and outline
    # ------------------------------------------------------------------
    for_all = match(mod, ops={"scf.forall"})
    func = transform.get_parent_op(anytype, for_all, op_name="func.func")

    wg_loops = match_and_split(mod, ops={"scf.forall"})
    for wg_loop in wg_loops:
        wg_loop = loop.loop_forall_to_parallel([anytype], wg_loop)
    func = transform.get_parent_op(anytype, wg_loop)

    func = apply_registered_pass(func, "gpu-map-parallel-loops")
    func = apply_registered_pass(func, "convert-parallel-loops-to-gpu")
    func = apply_registered_pass(func, "lower-affine")
    transform.apply_cse(func)
    canonicalize(func)

    launch_op = match_and_split(func, ops={"gpu.launch"})
    sg_rows = parameters["sg_rows"]
    subgroup_size = parameters["subgroup_size"]
    num_subgroups = wg_rows // sg_rows
    num_threads = num_subgroups * subgroup_size
    xegpu.set_gpu_launch_threads(launch_op[0], threads=[num_threads, 1, 1])

    func = apply_registered_pass(func, "lower-affine")
    canonicalize(func)
    func = apply_registered_pass(func, "gpu-launch-sink-index-computations")
    mod = apply_registered_pass(mod, "gpu-kernel-outlining")
    transform.apply_cse(mod)

    if stop_at_stage == "gpu-outlining":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Convert vector to xegpu
    # ------------------------------------------------------------------
    mod = apply_registered_pass(
        mod,
        "xevm-attach-target",
        options={"O": "3", "chip": "bmg"},
    )

    gpu_mod_ops = match_and_split(mod, ops={"gpu.module"})
    for gpu_mod in gpu_mod_ops:
        gpu_func = match(gpu_mod, ops={"gpu.func"})
        gpu_func = apply_registered_pass(gpu_func, "convert-vector-to-xegpu")
        transform.apply_cse(gpu_func)
        gpu_func = apply_registered_pass(gpu_func, "loop-invariant-code-motion")

    # Insert prefetches for the K/V tiles of every reduction loop.
    nb_prefetch = parameters.get("nb_prefetch", 1)
    if nb_prefetch > 0:
        # loop 1 and 2 load K only, loop 3 loads K and V.
        reduction_loops = match_and_split(gpu_func, ops={"scf.for"}, nhandles=3)
        for kv_loop, nloads in zip(reduction_loops, [1, 1, 2]):
            load_ops = match_and_split(kv_loop, ops={"xegpu.load_nd"}, nhandles=nloads)
            for load_op in load_ops:
                xegpu.insert_prefetch(load_op, nb_prefetch=nb_prefetch)
        transform.apply_cse(gpu_func)
        canonicalize(gpu_func)

    if stop_at_stage == "xegpu-initial":
        raise PipelineInterrupt()

    # ------------------------------------------------------------------
    # Work group level xegpu layouts
    # ------------------------------------------------------------------
    n_head = parameters["n_head"]

    # Q, the scores and the output are [wg_rows, *] tiles split by rows over the
    # subgroups; each subgroup owns whole rows so all three row reductions stay
    # subgroup local.
    q_sg_layout = [num_subgroups, 1]
    q_sg_data = [sg_rows, n_head]
    q_load_inst_data = [min(16, sg_rows), 32]

    out_sg_layout = q_sg_layout
    out_sg_data = q_sg_data

    qk_sg_layout = q_sg_layout
    # The max/sum passes may use a different kv tile size than the P@V pass, so
    # every kv-tile shaped layout is per-pass.
    pass_tiles = [softmax_kv_tile, softmax_kv_tile, kv_tile]

    # The K and V tiles are consumed in full by every subgroup.
    kv_sg_layout = [1, 1]
    v_load_inst_data = [32, 32]
    # Load K column-major so that the transpose feeding the DPAS is a no-op.
    k_load_order = [0, 1]

    prefetch_sg_layout = [4, 2]

    store_nd_op = match_and_split(gpu_func, ops={"xegpu.store_nd"}, nhandles=1)[0]
    xegpu.set_anchor_layout(
        store_nd_op,
        sg_layout=out_sg_layout,
        sg_data=out_sg_data,
    )

    # 5 loads: Q, then the K tile of each of the three loops, then the V tile.
    load_nd_ops = match_and_split(gpu_func, ops={"xegpu.load_nd"}, nhandles=5)
    xegpu.set_anchor_layout(
        load_nd_ops[0],
        sg_layout=q_sg_layout,
        sg_data=q_sg_data,
        inst_data=q_load_inst_data,
    )
    for k_load, tile in zip(load_nd_ops[1:4], pass_tiles):
        xegpu.set_anchor_layout(
            k_load,
            sg_layout=kv_sg_layout,
            sg_data=[tile, n_head],
            order=k_load_order,
        )
    xegpu.set_anchor_layout(
        load_nd_ops[4],
        sg_layout=kv_sg_layout,
        sg_data=[kv_tile, n_head],
        inst_data=v_load_inst_data,
    )

    if nb_prefetch > 0:
        # Every prefetched load contributes nb_prefetch prefetches ahead of its
        # loop plus one inside it, and the ops appear grouped per loop in walk
        # order. The last group covers both the K and the V load of the P@V loop.
        per_load = nb_prefetch + 1
        prefetch_ops = match_and_split(
            gpu_func, ops={"xegpu.prefetch_nd"}, nhandles=4 * per_load
        )
        prefetch_groups = [
            (prefetch_ops[:per_load], softmax_kv_tile),
            (prefetch_ops[per_load : 2 * per_load], softmax_kv_tile),
            (prefetch_ops[2 * per_load :], kv_tile),
        ]
        for group, tile in prefetch_groups:
            sg_data = [tile // prefetch_sg_layout[0], n_head // prefetch_sg_layout[1]]
            for prefetch_op in group:
                xegpu.set_anchor_layout(
                    prefetch_op,
                    sg_layout=prefetch_sg_layout,
                    sg_data=sg_data,
                    inst_data=list(sg_data),
                )

    # 4 dpas ops: Q@K^T in each of the three loops, then P@V.
    dpas_ops = match_and_split(gpu_func, ops={"xegpu.dpas"}, nhandles=4)
    for qk_dpas_op, tile in zip(dpas_ops[:3], pass_tiles):
        xegpu.set_anchor_layout(
            qk_dpas_op,
            sg_layout=q_sg_layout,
            sg_data=q_sg_data,
            index=0,
        )
        xegpu.set_anchor_layout(
            qk_dpas_op,
            sg_layout=kv_sg_layout,
            sg_data=[n_head, tile],
            index=1,
        )
        xegpu.set_anchor_layout(
            qk_dpas_op,
            sg_layout=qk_sg_layout,
            sg_data=[sg_rows, tile],
            index=2,
        )

    pv_dpas_op = dpas_ops[3]
    xegpu.set_anchor_layout(
        pv_dpas_op,
        sg_layout=qk_sg_layout,
        sg_data=[sg_rows, kv_tile],
        index=0,
    )
    xegpu.set_anchor_layout(
        pv_dpas_op,
        sg_layout=kv_sg_layout,
        sg_data=[kv_tile, n_head],
        index=1,
    )
    xegpu.set_anchor_layout(
        pv_dpas_op,
        sg_layout=out_sg_layout,
        sg_data=out_sg_data,
        index=2,
    )

    # Unroll the reduction loops for instruction level parallelism. This runs
    # last so that the op counts used for the layout anchors above still hold;
    # the layout attributes are carried over to the unrolled copies.
    unroll_factor = parameters.get("unroll_factor", 1)
    if unroll_factor > 1:
        kv_loops = match_and_split(gpu_func, ops={"scf.for"}, nhandles=3)
        for kv_loop in kv_loops:
            loop.loop_unroll(kv_loop, factor=unroll_factor)
        transform.apply_cse(gpu_func)
        canonicalize(gpu_func)

    if stop_at_stage == "xegpu-wg":
        raise PipelineInterrupt()

    return mod
